server {
    listen 80;
    root /var/www/public;

    # Terminal (ttyd) - letakkan sebelum / agar diprioritaskan
    location /terminal/ {
        proxy_pass http://100.125.64.93:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend (Flutter Web)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend Storage Files
    location ~ ^/be/storage/(.*)$ {
        alias /var/www/storage/app/public/$1;
    }


    # Backend API (Laravel) - Langsung ke PHP-FPM, strip prefix /be/
    location ~ ^/be/(.*)$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param SCRIPT_NAME     /index.php;
        fastcgi_param REQUEST_URI     /$1$is_args$args;
        fastcgi_param DOCUMENT_ROOT  /var/www/public;
    }
}
